# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"FastParser": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ncoop57.github.io/fast_trees/"

git_url = "https://github.com/ncoop57/fast_trees/tree/main/"

def custom_doc_links(name): return None
