# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_queries.ipynb (unless otherwise specified).

__all__ = ['JavaQueries']

# Cell
class JavaQueries:
    get_method_parameters = "(formal_parameter name: (identifier) @function.parameter)"
    get_all_comments = "(comment) @function.comment"